#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*              linuxserver/minisatip                 *
*                                                    *
*   https://hub.docker.com/r/linuxserver/minisatip   *
*                                                    *
*  https://github.com/linuxserver/docker-minisatip   *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
